# Production build (main branch)
# Note: Auto-publishing is disabled for production
# Deploy manually from Netlify dashboard
[build]
  command = "npm run build"
  publish = ".next"
  ignore = "exit 0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production]
  # Manual deploys only for production
  autoPublish = false

# QA Environment (qa branch)
[context.qa]
  command = "npm run build"

[context.qa.environment]
  NEXT_PUBLIC_ENV = "qa"

# Development Environment (development branch)
[context.development]
  command = "npm run build"

[context.development.environment]
  NEXT_PUBLIC_ENV = "development"

# Branch deploy previews
[context.branch-deploy]
  command = "npm run build"

# Deploy previews from pull requests
[context.deploy-preview]
  command = "npm run build"
