name: Deploy to Netlify via GitHub Actions

on:
  push:
    branches:
      - development
      - qa
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Netlify

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js application
        run: npm run build
        env:
          NEXT_PUBLIC_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/qa' && 'qa' || 'development' }}

      - name: Deploy to Netlify (Development)
        if: github.ref == 'refs/heads/development'
        uses: South-Paw/action-netlify-cli@v2
        with:
          args: deploy --build --alias development
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Deploy to Netlify (QA)
        if: github.ref == 'refs/heads/qa'
        uses: South-Paw/action-netlify-cli@v2
        with:
          args: deploy --build --alias qa
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Deploy to Netlify (Production)
        if: github.ref == 'refs/heads/main'
        uses: South-Paw/action-netlify-cli@v2
        with:
          args: deploy --build --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
